/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Cliente;
import aplicacion.FachadaAplicacion;
import aplicacion.Mensaje;
import aplicacion.Usuario;
import java.awt.ComponentOrientation;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.ArrayList;
import javafx.scene.paint.Color;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;

/**
 *
 * @author christiancp
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    private FachadaAplicacion fa;
    private Usuario usuario; // Usuario autenticado
    private ArrayList<Cliente> matches;
    private ArrayList<Cliente> victimas; // Gente mostrada en Inicio
    private Cliente ultimaVictima; // Última persona mostrada (para poder retroceder)

    public VPrincipal(FachadaAplicacion fa) {
        initComponents();
        initStyle();
        this.fa = fa;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        disLikeBtn = new javax.swing.JButton();
        likeBtn = new javax.swing.JButton();
        deshacerLike = new javax.swing.JButton();
        imagenUsuarioInicio = new javax.swing.JLabel();
        superlikeBtn = new javax.swing.JButton();
        btnFotoAnterior = new javax.swing.JButton();
        btnFotoSiguiente = new javax.swing.JButton();
        txtDatos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        mmtabbedpane = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        enviarMensaje = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMatches = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        deshacerMatch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        chatMsgs = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        sendBtn = new javax.swing.JButton();
        nombreUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jScrollPane3.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono derivative Powerline", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2.png"))); // NOI18N
        jLabel1.setText("Info-Tinder");

        jTabbedPane2.setBackground(new java.awt.Color(0, 51, 255));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Perfil", new javax.swing.ImageIcon(getClass().getResource("/Imagenes/profile.png")), jPanel1); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        disLikeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dislike_grande.png"))); // NOI18N
        disLikeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disLikeBtnActionPerformed(evt);
            }
        });

        likeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/like_grande.png"))); // NOI18N
        likeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeBtnActionPerformed(evt);
            }
        });

        deshacerLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backward.png"))); // NOI18N
        deshacerLike.setContentAreaFilled(false);
        deshacerLike.setEnabled(false);
        deshacerLike.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backwardPressed.png"))); // NOI18N
        deshacerLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deshacerLikeActionPerformed(evt);
            }
        });

        imagenUsuarioInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenUsuarioInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/no_image.png"))); // NOI18N
        imagenUsuarioInicio.setText("No queda más gente a quien le puedas interesar <3");
        imagenUsuarioInicio.setToolTipText("");
        imagenUsuarioInicio.setMaximumSize(new java.awt.Dimension(200, 400));
        imagenUsuarioInicio.setMinimumSize(new java.awt.Dimension(200, 400));

        superlikeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/corazon_peq.png"))); // NOI18N
        superlikeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superlikeBtnActionPerformed(evt);
            }
        });

        btnFotoAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backward.png"))); // NOI18N
        btnFotoAnterior.setContentAreaFilled(false);
        btnFotoAnterior.setEnabled(false);
        btnFotoAnterior.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backwardPressed.png"))); // NOI18N
        btnFotoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoAnteriorActionPerformed(evt);
            }
        });

        btnFotoSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/forward.png"))); // NOI18N
        btnFotoSiguiente.setContentAreaFilled(false);
        btnFotoSiguiente.setEnabled(false);
        btnFotoSiguiente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/forwardPressed.png"))); // NOI18N
        btnFotoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoSiguienteActionPerformed(evt);
            }
        });

        txtDatos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        txtDatos.setText("Nombre, Edad");

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setText("SO, Lenguaje\nDescripción\n");
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setEnabled(false);
        jScrollPane2.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(likeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deshacerLike, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(superlikeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(disLikeBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnFotoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(imagenUsuarioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFotoSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDatos)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagenUsuarioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnFotoAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFotoSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(disLikeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(likeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deshacerLike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(superlikeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );

        disLikeBtn.getAccessibleContext().setAccessibleName("Dislike");

        jTabbedPane2.addTab("Inicio", new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_peq.png")), jPanel2); // NOI18N

        mmtabbedpane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mmtabbedpaneStateChanged(evt);
            }
        });
        mmtabbedpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmtabbedpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mmtabbedpaneMouseEntered(evt);
            }
        });

        enviarMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviarMensaje.png"))); // NOI18N
        enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMensajeActionPerformed(evt);
            }
        });

        tablaMatches.setModel(new ModeloTablaMatches());
        tablaMatches.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaMatchesAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaMatches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMatchesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMatches);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        deshacerMatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unmatch.png"))); // NOI18N
        deshacerMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deshacerMatchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel4.setText("Escribe el nombre de la persona que buscas...");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enviarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deshacerMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deshacerMatch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enviarMensaje, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 87, Short.MAX_VALUE))
        );

        mmtabbedpane.addTab("Matches", jPanel6);

        chatMsgs.setColumns(20);
        chatMsgs.setRows(5);
        jScrollPane4.setViewportView(chatMsgs);

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane5.setViewportView(texto);

        sendBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sendBtn.png"))); // NOI18N
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        nombreUsuario.setFont(new java.awt.Font("Space Mono", 0, 18)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(0, 0, 255));
        nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuario.setText("Gustava F.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mmtabbedpane.addTab("Mensajes", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mmtabbedpane)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mmtabbedpane)
        );

        mmtabbedpane.getAccessibleContext().setAccessibleName("Tab");

        jTabbedPane2.addTab("Chats", new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chat.png")), jPanel3); // NOI18N

        jTabbedPane2.setSelectedComponent(jPanel2);

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reportar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Inicio");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initStyle() {
        disLikeBtn.setBorderPainted(false);
        disLikeBtn.setContentAreaFilled(false);
        disLikeBtn.setFocusPainted(false);
        disLikeBtn.setOpaque(false);

        likeBtn.setBorderPainted(false);
        likeBtn.setContentAreaFilled(false);
        likeBtn.setFocusPainted(false);
        likeBtn.setOpaque(false);

        deshacerLike.setBorderPainted(false);
        deshacerLike.setContentAreaFilled(false);
        deshacerLike.setFocusPainted(false);
        deshacerLike.setOpaque(false);

        sendBtn.setBorderPainted(false);
        sendBtn.setContentAreaFilled(false);
        sendBtn.setFocusPainted(false);
        sendBtn.setOpaque(false);

        deshacerMatch.setBorderPainted(false);
        deshacerMatch.setContentAreaFilled(false);
        deshacerMatch.setFocusPainted(false);
        deshacerMatch.setOpaque(false);

        enviarMensaje.setBorderPainted(false);
        enviarMensaje.setContentAreaFilled(false);
        enviarMensaje.setFocusPainted(false);
        enviarMensaje.setOpaque(false);

        chatMsgs.setForeground(java.awt.Color.blue);
        chatMsgs.setEditable(false);

        mmtabbedpane.setEnabledAt(1, false);
    }

    private void appendToPane(String usuario, String msg) {
        chatMsgs.append(usuario + ": " + msg + "\n");
    }

    private void deletePaneText() {
        chatMsgs.setText("");
    }

    private void disLikeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_disLikeBtnActionPerformed
        fa.insertarGusta((Cliente) this.usuario, this.victimas.get(0), false);
        this.eliminaVictima();
        this.recarga();
    }// GEN-LAST:event_disLikeBtnActionPerformed

    private void likeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_likeBtnActionPerformed
        fa.insertarGusta((Cliente) this.usuario, this.victimas.get(0), true);
        this.eliminaVictima();
        this.recarga();
    }// GEN-LAST:event_likeBtnActionPerformed

    private void deshacerLikeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deshacerLikeActionPerformed
        fa.deshacerMeGusta((Cliente) this.usuario);
        this.restauraVictima();
        this.recarga();
    }// GEN-LAST:event_deshacerLikeActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        if (texto.getText().length() > 0) {
            appendToPane("Yo", texto.getText());
            texto.setText("");
        }
    }// GEN-LAST:event_sendBtnActionPerformed

    private void enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enviarMensajeActionPerformed
        // TODO add your handling code here:
        deletePaneText();
        mmtabbedpane.setSelectedIndex(1);
        String nombreTxt = tablaMatches.getModel().getValueAt(tablaMatches.getSelectedRow(), 2).toString();
        String nombreUsuarioTxt = tablaMatches.getModel().getValueAt(tablaMatches.getSelectedRow(), 1).toString();
        nombreUsuario.setText(nombreTxt);
        ArrayList<Mensaje> mensajes = fa.consultarMensajes(usuario.getNombreUsuario(), nombreUsuarioTxt);
        mensajes.forEach((mensaje) -> {
            appendToPane(mensaje.getUsuarioAutor(), mensaje.getTexto());
        });
    }// GEN-LAST:event_enviarMensajeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void deshacerMatchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deshacerMatchActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_deshacerMatchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // this.dispose();
        // this.fa.iniciaInterfazUsuario();
        System.exit(0);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        // Faltaría añadir como segundo paráetro el nombre del que se quiere reportar
        // VReporte aux= new VReporte(this.usuario.getNombre(),);
    }// GEN-LAST:event_jButton2ActionPerformed

    private void superlikeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superlikeBtnActionPerformed
        if(fa.puedeDarSuperlike((Cliente)this.usuario)){
            fa.insertarSuperlike((Cliente)this.usuario, this.victimas.get(0));
            this.eliminaVictima();
        }
        else{
            fa.muestraExcepcion("Se habían agotado los SuperLike diarios.");
        }
        this.ultimaVictima = null; //Al ser superlike no se debe poder deshacer
        this.recarga();
        
    }//GEN-LAST:event_superlikeBtnActionPerformed

    private void btnFotoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFotoAnteriorActionPerformed

    private void btnFotoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFotoSiguienteActionPerformed

    
    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario u) {
        this.usuario = u;
    }

    // Carga usuarios compatibles con el usuario autenticado y sus fotos
    public void cargarUsuariosInicio() {
        this.victimas = fa.consultarUsuariosCompatibles((Cliente) this.usuario);
        for (Cliente c : this.victimas) {
            c.setFotos(fa.obtenerFotos(c));
        }
    }

    // Borra la víctima que se está mostrando
    public void eliminaVictima() {
        this.ultimaVictima = this.victimas.get(0);
        this.victimas.remove(0);
    }

    // Cuando se deshace megusta se vuelve a la víctima anterior
    public void restauraVictima() {
        this.victimas.add(0, this.ultimaVictima);
        this.ultimaVictima = null;
    }
    
    //Recarga la interfaz según la nueva lista de víctimas
    public void recarga(){
        if(this.victimas.size() == 0){ //No queda más gente a quien ver
            this.imagenUsuarioInicio.setIcon(null);
            this.disLikeBtn.setEnabled(false);
            this.likeBtn.setEnabled(false);
            this.superlikeBtn.setEnabled(false);
            this.btnFotoAnterior.setEnabled(false);
            this.btnFotoSiguiente.setEnabled(false);
            this.txtDatos.setText(null);
            this.txtDescripcion.setText(null);
            return;
        }
        Cliente vActual = this.victimas.get(0);
        
        //Habilita botones 
        this.likeBtn.setEnabled(true);
        this.disLikeBtn.setEnabled(true);

        // Habilita botón de superlike
        this.superlikeBtn.setEnabled(fa.puedeDarSuperlike((Cliente) this.usuario));

        // Habilita botón de deshacer
        this.deshacerLike.setEnabled(this.ultimaVictima != null);
        
        //Actualiza datos
        this.txtDatos.setText(vActual.getNombre() + ", " + vActual.getEdad());
        this.txtDescripcion.setText(vActual.getSOFav() + ", " + vActual.getLenguajeProgFav() + "\n" + vActual.getDescripcion());
        
        //Actualiza fotos
        ImageIcon img;
        if(vActual.getFotos().size() == 0){ //Sin fotos
            img = new ImageIcon(getClass().getResource("/Imagenes/no_image.png"));
            this.btnFotoAnterior.setEnabled(false);
            this.btnFotoSiguiente.setEnabled(false);
        }
        else{
            if(vActual.getFotos().size() > 1){
                this.btnFotoSiguiente.setEnabled(false);
            }
            img = vActual.getFotos().get(0).getImg();
        }
        // Escala la imagen
        Image aux = img.getImage();
        aux = aux.getScaledInstance(imagenUsuarioInicio.getWidth(), imagenUsuarioInicio.getHeight(), Image.SCALE_FAST);
        img = new ImageIcon(aux);
        this.imagenUsuarioInicio.setIcon(img);
        
        
        
    }
    

    private void tablaMatchesAncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_tablaMatchesAncestorAdded
        // TODO add your handling code here:
        matches = fa.consultarMatches(usuario);
        ModeloTablaMatches m = (ModeloTablaMatches) tablaMatches.getModel();
        m.setFilas(matches);
    }// GEN-LAST:event_tablaMatchesAncestorAdded

    private void mmtabbedpaneStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_mmtabbedpaneStateChanged
        // TODO add your handling code here:

        // TODO add your handling code here:
        if (mmtabbedpane.getSelectedIndex() == 1) {
            if (tablaMatches.getModel().getValueAt(tablaMatches.getSelectedRow(), 0) != null) {
                deletePaneText();
                mmtabbedpane.setSelectedIndex(1);
                String nombreTxt = tablaMatches.getModel().getValueAt(tablaMatches.getSelectedRow(), 2).toString();
                String nombreUsuarioTxt = tablaMatches.getModel().getValueAt(tablaMatches.getSelectedRow(), 1)
                        .toString();
                nombreUsuario.setText(nombreTxt);
                ArrayList<Mensaje> mensajes = fa.consultarMensajes(usuario.getNombreUsuario(), nombreUsuarioTxt);
                mensajes.forEach((mensaje) -> {
                    appendToPane(mensaje.getUsuarioAutor(), mensaje.getTexto());
                });
            } else {
                mmtabbedpane.setEnabledAt(1, false);
            }
        }
    }// GEN-LAST:event_mmtabbedpaneStateChanged

    private void tablaMatchesMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tablaMatchesMouseClicked

    }// GEN-LAST:event_tablaMatchesMouseClicked

    private void mmtabbedpaneMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_mmtabbedpaneMouseEntered

    }// GEN-LAST:event_mmtabbedpaneMouseEntered

    private void mmtabbedpaneMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_mmtabbedpaneMouseClicked
        if (mmtabbedpane.getSelectedIndex() == 1) {

        }
    }// GEN-LAST:event_mmtabbedpaneMouseClicked


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFotoAnterior;
    private javax.swing.JButton btnFotoSiguiente;
    private javax.swing.JTextArea chatMsgs;
    private javax.swing.JButton deshacerLike;
    private javax.swing.JButton deshacerMatch;
    private javax.swing.JButton disLikeBtn;
    private javax.swing.JButton enviarMensaje;
    private javax.swing.JLabel imagenUsuarioInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton likeBtn;
    private javax.swing.JTabbedPane mmtabbedpane;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton superlikeBtn;
    private javax.swing.JTable tablaMatches;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel txtDatos;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
